### PR TITLE
Add Hebrew translation

### PR DESCRIPTION
**Pull request by GreenLunar**

### CODE REVIEW

**Comment by GreenLunar** [comment]
Oops! I did not meant to result in such commit.

I am closing this PR.  Please cut&paste my changes, if you will.

**Comment by jannispinter** [comment]
Thanks! I fixed the deleted file.

**Comment by GreenLunar** [comment]
You have deleted values-de.

**Comment by GreenLunar** [comment]
Thanks.

**Comment by GreenLunar** [comment]
values-de is still gone.

**Pull request merged**
